# Generated by Django 5.0.6 on 2024-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=80)),
                ('paterno', models.CharField(max_length=30)),
                ('materno', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
    ]
