# Generated by Django 5.0.6 on 2024-10-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='run',
            new_name='rut',
        ),
    ]
