# Generated by Django 5.0.6 on 2024-11-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_run_usuario_rut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
