# Generated by Django 5.0.6 on 2024-11-07 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.CharField(db_column='idTipo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=80)),
                ('paterno', models.CharField(max_length=30)),
                ('materno', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
                ('tipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
        ),
    ]
